- id: go-unit-tests
  name: 'go-unit-tests'
  entry: go/unit-tests.sh
  files: '\.go$'
  language: 'script'
  description: "Runs `go test`"
- id: go-unit-tests-all
  name: 'go-unit-tests-all'
  entry: go/unit-tests-all.sh
  files: '\.go$'
  language: 'script'
  description: "Runs `go test all`"
- id: python-unit-tests
  name: 'python-unit-test'
  entry: python/unit-tests.sh
  files: '\.py$'
  language: 'script'
  description: "Runs `pytest`"
